# Generated by Django 4.1.dev20211207123650 on 2022-01-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('useraccount', models.CharField(max_length=200)),
                ('password2', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
