# Generated by Django 4.1.dev20211207123650 on 2022-01-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_useraccount_userregister_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userRegister',
        ),
    ]
