# Generated by Django 4.1.dev20211207123650 on 2022-01-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_delete_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='mCreatepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
