# Generated by Django 4.0.2 on 2022-02-14 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcreatepost',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcreatepost',
            name='datepost',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
