# Generated by Django 4.0.2 on 2022-02-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_mcreatepost_author_mcreatepost_datepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcreatepost',
            name='author',
        ),
    ]
